// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

const String _webFirebaseApiKey = String.fromEnvironment(
  'SCREENLINK_FIREBASE_WEB_API_KEY',
  defaultValue: '',
);

const String _androidFirebaseApiKey = String.fromEnvironment(
  'SCREENLINK_FIREBASE_ANDROID_API_KEY',
  defaultValue: '',
);

const String _iosFirebaseApiKey = String.fromEnvironment(
  'SCREENLINK_FIREBASE_IOS_API_KEY',
  defaultValue: '',
);

const String _macosFirebaseApiKey = String.fromEnvironment(
  'SCREENLINK_FIREBASE_MACOS_API_KEY',
  defaultValue: '',
);

const String _windowsFirebaseApiKey = String.fromEnvironment(
  'SCREENLINK_FIREBASE_WINDOWS_API_KEY',
  defaultValue: '',
);

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webFirebaseApiKey,
    appId: '1:557179503430:web:0ff03c56eac8abf88fdb47',
    messagingSenderId: '557179503430',
    projectId: 'screenlink-f2484',
    authDomain: 'screenlink-f2484.firebaseapp.com',
    storageBucket: 'screenlink-f2484.firebasestorage.app',
    measurementId: 'G-HEZ5SZ711X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidFirebaseApiKey,
    appId: '1:557179503430:android:6042793b4fa3f0068fdb47',
    messagingSenderId: '557179503430',
    projectId: 'screenlink-f2484',
    storageBucket: 'screenlink-f2484.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosFirebaseApiKey,
    appId: '1:557179503430:ios:0de95a2275e99dbd8fdb47',
    messagingSenderId: '557179503430',
    projectId: 'screenlink-f2484',
    storageBucket: 'screenlink-f2484.firebasestorage.app',
    iosBundleId: 'com.example.screenlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _macosFirebaseApiKey,
    appId: '1:557179503430:ios:0de95a2275e99dbd8fdb47',
    messagingSenderId: '557179503430',
    projectId: 'screenlink-f2484',
    storageBucket: 'screenlink-f2484.firebasestorage.app',
    iosBundleId: 'com.example.screenlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _windowsFirebaseApiKey,
    appId: '1:557179503430:web:1edb29ffba30652d8fdb47',
    messagingSenderId: '557179503430',
    projectId: 'screenlink-f2484',
    authDomain: 'screenlink-f2484.firebaseapp.com',
    storageBucket: 'screenlink-f2484.firebasestorage.app',
    measurementId: 'G-FT1Q7FM2J8',
  );
}
